### ISSUE TITLE
Issues with absolute paths and mkdir

### ISSUE THREAD

**Issue by WocketSesh** [teeworlds-utilities/teeworlds-utilities#6]
I tried making a pull request at first but ended up just making a massive mess.

There are two issues in saveCanvas (https://github.com/teeworlds-utilities/teeworlds-utilities/blob/master/lib/utils/canvas.ts#L103) , the first being if you use an absolute path ie: "/somedir1/somedir2/", when split the first entry in the array will be "" causing an error on mkdir.
The second being when you are making a directory that doesn't exist, you are making all the "nested" directories inside the current directory, rather than one inside the other.
So "somedir1/somedir2/" would result in

parent
├── somedir1
└── somedir2

rather than

parent
├── somedir1
│   └── somedir2

**Comment by theobori** [comment]
Thanks !

I fixed this, the fix it should appear in the next release (1.1.7) with other changes.
